---
- name: download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer
  tags: composer

- name: install composer
  shell: cat /tmp/installer | php -- --install-dir=/home/{{ webserver_user }}/bin
  args:
    creates: /home/{{ webserver_user }}/bin/composer.phar
  tags: composer
  become: yes

- name: rename composer.phar to composer
  shell: mv /home/{{ webserver_user }}/bin/composer.phar /home/{{ webserver_user }}/bin/composer
  args:
    creates: /home/{{ webserver_user }}/bin/composer
  tags: composer
  become: yes

- name: make composer executable
  file:
    path: /home/{{ webserver_user }}/bin/composer
    mode: a+x
    owner: "{{ webserver_user }}"
    group: "{{ webserver_user }}"
    state: file
  tags: composer
  become: yes